### ISSUE TITLE
tests.spec.js incomplete starting point

### ISSUE THREAD

**Issue by dakotaraymccoy** [enartey/WebAppsLabs#4]
The readme file says we should have a describe section in our tests.spec.js file, but all that's in that file is this:

try {
   var chai = require('./chai.js');
   var expect = chai.expect;
   var methods = require('./yourCode.js');
   var binarySearch = methods.binarySearch;
   var countTags = methods.countTags;
   var extractHashTags = methods.extractHashTags;
} catch (e) {}

// Do not change anything above this line

Did we not download the files properly?

**Comment by skiadas** [comment]
@dakotaraymccoy We answered this in class but might as well see if emailing of issue comments works. 

As we said in class, that point in the instructions describes a certain piece of code that you were supposed to find there. Just copy and paste it from the instructions.

P.S. I think I know what sort of happened. If you had created the issue at **my** WebAppsLabs repository, https://github.com/skiadas/WebAppsLabs then I would have probably received an email. Since you put it in Edwin's fork, I did not. But including @skiadas would always catch my attention.
