### ISSUE TITLE
redo

### ISSUE THREAD

**Issue by enartey** [enartey/WebAppsLabs#68]
Advances "current" to the next item, and executes the command there. Should throw an error if there is no next item.

**Comment by enartey** [comment]
@Skiadas, the test for redo is not recognizing the error it is supposed to receive when run on an empty list. 

``` Javascript
redo: function(){
    if (this.list.isLast(this.current)){
        throw new Error("No next item for redo");
    }
    this.current = this.current.next;
    this.current.value.execute();
}

```

Test:

``` Javascript
beforeEach(function(){
        cmd = mockCommand();
        H1 = CmdHistory.new();
        H1.add(cmd);
        H2 = CmdHistory.new();
    });
it("redo() issue #68", function(){
        var cmd2 = mockCommand();
        H1.add(cmd2);
        expect(H1.current.value).to.equal(cmd2);
        H1.redo();
        expect(H1.current.value).to.equal(cmd);
        H1.redo();
        expect(H1.current.value).to.equal(null);
        expect(H2.redo()).to.throw(Error);
    });

```

![screen shot 2015-03-21 at 12 39 59 pm](https://cloud.githubusercontent.com/assets/10490549/6765868/6c36f760-cfc7-11e4-8cec-e86af3ff775d.png)

**Comment by skiadas** [comment]
You have to put on the left a function that when executed would throw the error. So more like:

expect(function() { badstuffhere(); }).to.throw(Error);

Otherwise the function gets evaluated before being passed to expect, so the error is thrown before the tester has a chance to look for it.

Haris Skiadas
Hanover College
